[package]
name = "tty_client"
description = "A simple client to call using the opus protocol."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
cpal = "0.15"
opus = "0.3.0"
sha2 = "0.10.9"
